language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- 'pypy'
env:
- DJANGO=django==1.8.*
- DJANGO=django==1.11.*
- DJANGO==2.0.*
- DJANGO=git+https://github.com/django/django.git\#egg=django
install:
- pip install $DJANGO
- python setup.py install
- pip install -r test_requirements.txt
script: python manage.py test
matrix:
  fast_finish: true
  allow_failures:
    # pypy testing is experimental
    - python: "pypy"

    # The latest version of django may just fail. That's fine, it's not stable
    - env: DJANGO=git+https://github.com/django/django.git\#egg=django

  exclude:
    # Django 1.8 doesn't support python 3.6
    - python: "3.6"
      env: DJANGO=django==1.8.*

    # Django 1.10 onward doesn't support python 3.3 or 3.4
    - python: "3.3"
      env: DJANGO=django==1.11.*
    - python: "3.4"
      env: DJANGO=django==1.11.*
    - python: "3.3"
      env: DJANGO==2.0.*
    - python: "3.4"
      env: DJANGO==2.0.*
    - python: "3.3"
      env: DJANGO=git+https://github.com/django/django.git\#egg=django
    - python: "3.4"
      env: DJANGO=git+https://github.com/django/django.git\#egg=django

    # Django 2.0 onward doesn't support python 2.7
    - python: "2.7"
      env: DJANGO==2.0.*
    - python: "2.7"
      env: DJANGO=git+https://github.com/django/django.git\#egg=django

    # Django 2.1 onward doesn't support python 3.5
    - python: "3.5"
      env: DJANGO=git+https://github.com/django/django.git\#egg=django

notifications:
  email: false
deploy:
  provider: pypi
  user: deep-c
  password:
    secure: cBcxZ1m/CL69+bbEaOJxdHImIcLRCRlsK1uiQvXfPss/E4hve07rH+272eHuctmajrzeTn10pUWGm5k7Yd2i+n+gs6IG71l8b24xn+EkZdfQ0xBJnhZnTy0hSV1ppplJL+Mey/zf4UNEKzVoNMzOz2c3MpSV/Yce2srgAaFuwagfcsOi7xgq0v2z1xim0MspJAd0IpO+r36TY1Est1wvoq6QcQEU9k+Y9LyJuM8ZCp/6plz3vMY3ZV+PdKDP4aDja08FSE57yGkc7qGSOrTew/Jy3XV7WekmYTCVM40XuLJYEfV2RSbIsyokNUk9TNRrW+DI/8MUcuUYgcD5pBFLORQJEd/ijVnlirhn6eehGNQShxiO98PsgeChoOtL7LzOKka4cxzXFMprSmeaTV5P5l8PfjPj5RU1+J4i83BxEfDwPPKHMY2gBrT15g1uFDIfP99/YN5FwXg3eK/Tn5WDVRmYfUCdBdFlVtCWDSetBn3WFFnntziG5B93EABBIMBvtCzQ/8nhgkXl1yKszwDYwNnETRHB0V0NpucR8HqKnBkSxdM0MQpeFi1eiMCfmLg4bHEKnF8GA+GysvhW/yQ+QAR2j+BUMlvUN58aWhKBGdBAkLgQawESl3rvAtw+L3763XZ2CvmCXER9FKNlFQVYVKidKBrlgblTFNE46FIH+Rc=
  on:
    tags: true
    branch: master
after_success:
- coveralls
